import { initializeApp } from 'https://www.gstatic.com/firebasejs/12.6.0/firebase-app.js';
import { getFirestore, doc, onSnapshot, runTransaction, setDoc } from 'https://www.gstatic.com/firebasejs/12.6.0/firebase-firestore.js';

const firebaseConfig={apiKey:'AIzaSyB_QSH4O4dQMOFdBx0gDPL7XL7DXNcW-TI',authDomain:'sales-race-kz.firebaseapp.com',projectId:'sales-race-kz',storageBucket:'sales-race-kz.firebasestorage.app',messagingSenderId:'354024847876',appId:'1:354024847876:web:ec5c3a2e7c0652ca5ad351'};
const db=getFirestore(initializeApp(firebaseConfig));
const raceRef=doc(db,'race','current');
const defaults={masterPlan:180,cities:[{id:'uka',name:'УКА',color:'uka',sales:0,plan:60},{id:'semey',name:'Семей',color:'semey',sales:0,plan:60},{id:'pavlodar',name:'Павлодар',color:'pavlodar',sales:0,plan:60}]};
let state=structuredClone(defaults),previousLeader=null;
const cheers=['Отличная работа! Каждая продажа приближает команду к финишу.','Сильный рывок! Так держать — победа строится из таких шагов.','Браво! Команда показывает настоящий темп чемпиона.','Есть результат! Ваша энергия двигает город вперёд.'];

function message(html){document.getElementById('notice').innerHTML=html}
function saveError(){message('<b>Не удалось сохранить изменение.</b> Проверьте Firestore → «Правила»: для теста должно быть <code>allow read, write: if true;</code>.')}
async function ensureRace(){await setDoc(raceRef,defaults,{merge:true})}
async function addSale(cityId,amount){try{await runTransaction(db,async transaction=>{const snapshot=await transaction.get(raceRef);const current=snapshot.exists()?snapshot.data():defaults;const cities=current.cities.map(city=>city.id===cityId?{...city,sales:Math.max(0,(city.sales||0)+amount)}:city);transaction.set(raceRef,{...current,cities,updatedAt:Date.now()})});const city=state.cities.find(item=>item.id===cityId);if(amount>0)message(`<b>🔥 ${city.name}, +${amount}!</b> ${cheers[Math.floor(Math.random()*cheers.length)]}`);else message(`<b>↩ ${city.name}: корректировка ${amount} продаж.</b> Результат обновлён.`)}catch(error){saveError()}}

function showLeader(city,oldLeader){const overlay=document.createElement('div');overlay.style.cssText='position:fixed;inset:0;z-index:30;background:#12202de8;color:#fff;display:grid;place-items:center;padding:24px;text-align:center';overlay.innerHTML=`<div><p style="color:#ccff42;font:800 13px Manrope;letter-spacing:1px">СМЕНА ЛИДЕРА</p><h2 style="font:700 clamp(34px,7vw,78px)/1 Unbounded,sans-serif;margin:16px 0">🏆 ${city.name}<br>ВПЕРЁД!</h2><p style="font:600 17px/1.5 Manrope;max-width:590px">${oldLeader?`${city.name} обогнал ${oldLeader.name}! ${oldLeader.name}, прибавляйте темп — финиш ещё впереди.`:`${city.name} первым выходит в лидеры! Остальным городам пора нажимать на газ.`}</p><button type="button" style="width:auto;background:#ccff42;color:#12202d;padding:15px 24px">Продолжаем гонку →</button></div>`;overlay.querySelector('button').onclick=()=>overlay.remove();document.body.append(overlay)}

function render(){const total=state.cities.reduce((sum,city)=>sum+city.sales,0);document.getElementById('total').textContent=`${total} / ${state.masterPlan}`;document.getElementById('totalLine').style.width=`${Math.min(100,total/state.masterPlan*100)}%`;document.getElementById('race').innerHTML=state.cities.map(city=>{const percent=Math.min(91,city.sales/city.plan*91);return `<article class="track" data-city="${city.id}" tabindex="0" role="button" aria-label="Добавить продажу городу ${city.name}" style="cursor:pointer"><div class="track-top"><div><div class="city">${city.name}</div><small>${Math.round(city.sales/city.plan*100)}% плана · план ${city.plan}</small></div><div class="score">${city.sales}<small> продаж</small></div></div><div class="road"><div class="progress" style="width:${100-Math.min(100,city.sales/city.plan*100)}%"></div><div style="position:absolute;right:3px;top:-29px;z-index:3;font-size:30px;line-height:1">🏁<small style="display:block;font-size:7px;font-weight:800">ФИНИШ</small></div><div class="car ${city.color}" style="left:${percent}%;${city.sales>=city.plan?'filter:drop-shadow(0 0 8px #ffcf31)':''}">${city.sales>=city.plan?'★':city.name}</div></div><button class="quick" type="button" style="position:absolute;right:25px;bottom:18px;width:auto;margin:0;background:#12202d;padding:7px 10px;z-index:4">+1 продажа</button></article>`}).join('');document.querySelectorAll('.track').forEach(track=>{const add=()=>addSale(track.dataset.city,1);track.onclick=event=>{if(!event.target.closest('.quick'))add()};track.onkeydown=event=>{if(event.key==='Enter'||event.key===' '){event.preventDefault();add()}};track.querySelector('.quick').onclick=add});const sorted=[...state.cities].sort((a,b)=>b.sales/b.plan-a.sales/a.plan);document.getElementById('board').innerHTML=sorted.map((city,index)=>`<li><span>${index===0?'🏆 ':''}${city.name}</span><b>${city.sales} / ${city.plan}</b></li>`).join('');document.getElementById('updated').textContent=new Date().toLocaleTimeString('ru-RU',{hour:'2-digit',minute:'2-digit'});if(sorted[0].sales>0&&previousLeader!==sorted[0].id){const old=previousLeader?state.cities.find(city=>city.id===previousLeader):null;previousLeader=sorted[0].id;showLeader(sorted[0],old)}}

function openCorrection(){const overlay=document.createElement('div');overlay.style.cssText='position:fixed;inset:0;z-index:30;background:#12202de8;color:#fff;display:grid;place-items:center;padding:20px;overflow:auto';overlay.innerHTML=`<form style="background:#fff;color:#12202d;padding:26px;width:min(470px,100%)"><p class="eyebrow">Только для руководителя</p><h2 style="font:700 22px Unbounded,sans-serif;margin:0 0 15px">Корректировка планов и продаж</h2><label style="display:block;font-weight:800;color:#147bff">Общий план месяца<input id="masterPlan" required min="1" type="number" value="${state.masterPlan}" style="display:block;width:100%;padding:11px;margin:5px 0 12px"></label>${state.cities.map(city=>`<fieldset style="border:1px solid #d5dcda;margin:10px 0;padding:10px"><legend style="font-weight:800">${city.name}</legend><label style="display:block;font-size:11px;font-weight:700">План<input data-plan="${city.id}" required min="1" type="number" value="${city.plan}" style="display:block;width:100%;padding:10px;margin:4px 0 9px"></label><label style="display:block;font-size:11px;font-weight:700">Фактические продажи<input data-sales="${city.id}" required min="0" type="number" value="${city.sales}" style="display:block;width:100%;padding:10px;margin-top:4px"></label></fieldset>`).join('')}<div style="display:flex;gap:10px;margin-top:15px"><button type="button" class="cancel" style="background:#e7eceb;color:#12202d">Отмена</button><button type="submit">Сохранить изменения</button></div><p class="error" style="color:#c51b1b;font-size:11px;min-height:16px"></p></form>`;overlay.querySelector('.cancel').onclick=()=>overlay.remove();overlay.querySelector('form').onsubmit=async event=>{event.preventDefault();const button=overlay.querySelector('[type="submit"]');button.disabled=true;button.textContent='Сохраняю…';try{const cities=state.cities.map(city=>({...city,plan:+overlay.querySelector(`[data-plan="${city.id}"]`).value,sales:+overlay.querySelector(`[data-sales="${city.id}"]`).value}));await setDoc(raceRef,{cities,masterPlan:+overlay.querySelector('#masterPlan').value,updatedAt:Date.now()},{merge:true});overlay.remove();message('<b>✅ Корректировка сохранена.</b> Планы и продажи обновлены у всех городов.')}catch(error){button.disabled=false;button.textContent='Сохранить изменения';overlay.querySelector('.error').textContent='Не удалось сохранить. Проверьте правила Firestore.'}};document.body.append(overlay)}

const correction=document.createElement('button');correction.textContent='⚙ Корректировать планы и продажи';correction.style.cssText='margin:0 7vw 20px;width:auto;background:#12202d;padding:12px 16px';correction.onclick=openCorrection;document.querySelector('.race').insertAdjacentElement('beforebegin',correction);document.getElementById('saleForm').onsubmit=event=>{event.preventDefault();addSale(document.getElementById('city').value,+document.getElementById('amount').value);event.target.reset();document.getElementById('amount').value=1};
if(location.protocol==='file:'){message('<b>Онлайн-база не запускается из файла.</b> Откройте опубликованную HTTPS-ссылку сайта, а не адрес file:///…')}else{onSnapshot(raceRef,snapshot=>{if(!snapshot.exists())ensureRace().catch(saveError);else{const data=snapshot.data();state={cities:data.cities||defaults.cities,masterPlan:data.masterPlan||180};render()}},saveError)}
